services:
  database:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "db_storage:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"

  api:
    depends_on:
      - database
    env_file:
      - ./.env
    build:
      context: ./
      dockerfile: ./CzechSkills2024.Api/Dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

#  frontend:
#    depends_on: 
#      - api
#      - database
#    restart: always
#    build:
#      context: ./
#      dockerfile: ./CzechSkills2024.Frontend/Dockerfile
#    ports:
#      - "3000:3000"
#    environment:
#      - NODE_ENV=production

volumes:
  db_storage:
    driver: local