// <auto-generated />
using CzechSkills2024.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CzechSkills2024.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241122135241_Three")]
    partial class Three
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CzechSkills2024.Database.Tables.Testing", b =>
                {
                    b.Property<string>("TestingId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TestingId");

                    b.ToTable("Testings");
                });

            modelBuilder.Entity("CzechSkills2024.Database.Tables.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserTestingId")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CzechSkills2024.Database.Tables.UserTesting", b =>
                {
                    b.Property<string>("UserTestingId")
                        .HasColumnType("text");

                    b.Property<string>("GameKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserTestingId");

                    b.HasIndex("TestingId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserTestings");
                });

            modelBuilder.Entity("CzechSkills2024.Database.Tables.UserTesting", b =>
                {
                    b.HasOne("CzechSkills2024.Database.Tables.Testing", "Testing")
                        .WithMany()
                        .HasForeignKey("TestingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CzechSkills2024.Database.Tables.User", "User")
                        .WithOne("UserTesting")
                        .HasForeignKey("CzechSkills2024.Database.Tables.UserTesting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Testing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CzechSkills2024.Database.Tables.User", b =>
                {
                    b.Navigation("UserTesting");
                });
#pragma warning restore 612, 618
        }
    }
}
